import { Container } from "unstated";

const initPages = [
  null,
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-001.png", id: 1 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-002.png", id: 2 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-003.png", id: 3 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-004.png", id: 4 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-005.png", id: 5 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-006.png", id: 6 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-007.png", id: 7 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-008.png", id: 8 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-009.png", id: 9 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-010.png", id: 10 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-011.png", id: 11 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-012.png", id: 12 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-013.png", id: 13 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-014.png", id: 14 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-015.png", id: 15 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-016.png", id: 16 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-017.png", id: 17 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-018.png", id: 18 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-019.png", id: 19 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-020.png", id: 20 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-021.png", id: 21 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-022.png", id: 22 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-023.png", id: 23 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-024.png", id: 24 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-025.png", id: 25 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-026.png", id: 26 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-027.png", id: 27 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-028.png", id: 28 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-029.png", id: 29 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-030.png", id: 30 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-031.png", id: 31 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-032.png", id: 32 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-033.png", id: 33 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-034.png", id: 34 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-035.png", id: 35 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-036.png", id: 36 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-037.png", id: 37 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-038.png", id: 38 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-039.png", id: 39 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-040.png", id: 40 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-041.png", id: 41 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-042.png", id: 42 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-043.png", id: 43 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-044.png", id: 44 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-045.png", id: 45 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-046.png", id: 46 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-047.png", id: 47 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-048.png", id: 48 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-049.png", id: 49 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-050.png", id: 50 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-051.png", id: 51 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-052.png", id: 52 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-053.png", id: 53 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-054.png", id: 54 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-055.png", id: 55 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-056.png", id: 56 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-057.png", id: 57 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-058.png", id: 58 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-059.png", id: 59 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-060.png", id: 60 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-061.png", id: 61 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-062.png", id: 62 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-063.png", id: 63 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-064.png", id: 64 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-065.png", id: 65 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-066.png", id: 66 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-067.png", id: 67 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-068.png", id: 68 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-069.png", id: 69 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-070.png", id: 70 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-071.png", id: 71 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-072.png", id: 72 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-073.png", id: 73 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-074.png", id: 74 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-075.png", id: 75 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-076.png", id: 76 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-077.png", id: 77 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-078.png", id: 78 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-079.png", id: 79 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-080.png", id: 80 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-081.png", id: 81 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-082.png", id: 82 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-083.png", id: 83 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-084.png", id: 84 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-085.png", id: 85 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-086.png", id: 86 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-087.png", id: 87 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-088.png", id: 88 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-089.png", id: 89 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-090.png", id: 90 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-091.png", id: 91 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-092.png", id: 92 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-093.png", id: 93 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-094.png", id: 94 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-095.png", id: 95 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-096.png", id: 96 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-097.png", id: 97 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-098.png", id: 98 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-099.png", id: 99 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-100.png", id: 100 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-101.png", id: 101 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-102.png", id: 102 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-103.png", id: 103 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-104.png", id: 104 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-105.png", id: 105 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-106.png", id: 106 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-107.png", id: 107 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-108.png", id: 108 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-109.png", id: 109 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-110.png", id: 110 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-111.png", id: 111 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-112.png", id: 112 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-113.png", id: 113 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-114.png", id: 114 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-115.png", id: 115 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-116.png", id: 116 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-117.png", id: 117 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-118.png", id: 118 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-119.png", id: 119 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-120.png", id: 120 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-121.png", id: 121 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-122.png", id: 122 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-123.png", id: 123 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-124.png", id: 124 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-125.png", id: 125 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-126.png", id: 126 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-127.png", id: 127 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-128.png", id: 128 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-129.png", id: 129 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-130.png", id: 130 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-131.png", id: 131 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-132.png", id: 132 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-133.png", id: 133 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-134.png", id: 134 },
  { url: "images/OnePiece/Sách vui dao-hai-tac-phan-1-135.png", id: 135 },
];
class FlipBookStore extends Container {
  state = {
    pageWidth: ((window.innerHeight - 165) / 29.7) * 21,
    pageHeight: window.innerHeight - 165,
    leftPage: 0,
    rightPage: 1,
    pages: initPages,
  };
}

const FlipBookContainer = new FlipBookStore();

export default FlipBookContainer;
